### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dfabreguette** [amiuhle/atom-redmine#4]
Getting the error bellow as I try to open plugin issues explorer (pressing CTRL+ALT+R + M).

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10
**Thrown From**: [redmine](https://github.com/amiuhle/atom-redmine) package, v0.2.1
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/davidfabreguette/.atom/packages/redmine/lib/fetch-redmine.js:52

TypeError: undefined is not a function
  at fetch (/Users/davidfabreguette/.atom/packages/redmine/lib/fetch-redmine.js:52:26)
  at Redmine.fetch (/Users/davidfabreguette/.atom/packages/redmine/lib/fetch-redmine.js:54:14)
  at Redmine.getIssues (/Users/davidfabreguette/.atom/packages/redmine/lib/fetch-redmine.js:61:19)
  at Object.listIssues (/Users/davidfabreguette/.atom/packages/redmine/lib/redmine.js:120:31)
  at atom-workspace.redmineAllIssues (/Users/davidfabreguette/.atom/packages/redmine/lib/redmine.js:76:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -3:21.9.0 core:paste (atom-text-editor#redmine.host.editor.mini.is-focused)
     -3:04.3.0 core:close (div.settings-view.pane-item)
     -2:19.4.0 fuzzy-finder:toggle-file-finder (table.package-keymap-table.table.native-key-bindings.text)
  4x -1:46.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:43.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:42.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -1:39.9.0 core:copy (div.package-readme.native-key-bindings)
     -1:39.4.0 pane:show-next-item (div.package-readme.native-key-bindings)
     -1:38.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:38.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -1:31.3.0 pane:show-next-item (div.settings-view.pane-item)
     -1:02.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:54.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:40.6.0 redmine:all-issues (table.package-keymap-table.table.native-key-bindings.text)
     -0:03.9.0 redmine:my-issues (div.settings-view.pane-item)
     -0:00.6.0 redmine:all-issues (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-color-highlight"
    ]
  },
  "redmine": {
    "apiKey": "http://redmine.appliserv.fr",
    "host": "fiQhXH1vNg9hADVXpjXu"
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
color-picker, v1.7.0
language-haml, v0.21.0
redmine, v0.2.1

# Dev
No dev packages
```

**Comment by amiuhle** [comment]
Unfortunately those stack traces don't make any sense. It shows incorrect line numbers.

Do you have a `.atom-redmine` config file with a correct `projectId`? Are the API Key and URL configured correctly in the settings?

**Comment by amiuhle** [comment]
@dfabreguette-ap You have the `apiKey` and the `host` mixed up in your config.
Also, you should probably renew your API key after it's been visible here.

**Comment by dfabreguette** [comment]
@amiuhle what do you mean by "mixed up" ?

Yes of course I'll change it ! :)

**Comment by amiuhle** [comment]
@dfabreguette-ap You have the API Key in the URL field and the URL in the API Key field

**Comment by dfabreguette** [comment]
@amiuhle Ohhhhhhh really sorry to take you time for that ! Guess I need some holidays !
