### ISSUE TITLE
unassigned issues

### ISSUE THREAD

**Issue by Aradiv** [amiuhle/atom-redmine#8]
1. Have unassignes issues in your redmine
2. open all issues (crtl+alt+r a) and try searching with Ticketnumber

**Atom Version**: 1.6.0
**System**: "CentOS Linux
**Thrown From**: [redmine](https://github.com/amiuhle/atom-redmine) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /home/eb/.atom/packages/redmine/lib/views/issues-list-view.js:75

TypeError: Cannot read property 'name' of undefined
    at Object.content (/home/eb/.atom/packages/redmine/lib/views/issues-list-view.js:75:38)
    at Builder.tag (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/home/eb/.atom/packages/redmine/lib/views/issues-list-view.js:67:14)
    at Builder.tag (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as li] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.<anonymous> (/home/eb/.atom/packages/redmine/lib/views/issues-list-view.js:64:12)
    at Function.View.buildHtml (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
    at Function.View.render (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:129:19)
    at exports.$$ (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:627:24)
    at IssuesListView.viewForItem (/home/eb/.atom/packages/redmine/lib/views/issues-list-view.js:63:12)
    at IssuesListView.module.exports.SelectListView.populateList (/home/eb/.atom/packages/redmine/node_modules/atom-space-pen-views/lib/select-list-view.js:206:29)
    at /home/eb/.atom/packages/redmine/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```
### Commands

```
     -2:03.2.0 redmine:my-issues (atom-text-editor.editor.is-focused)
     -1:59.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:59.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:59.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:58 redmine:all-issues (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:48.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:48.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.8.0 redmine:my-issues (atom-text-editor.editor.is-focused)
     -0:06.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 redmine:all-issues (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {},
  "redmine": {
    "apiKey": "241......................................",
    "host": "https://redmine......."
  }
}
```
### Installed Packages

``` coffee
# User
grunt-runner, v0.14.0
minimap, v4.21.0
redmine, v0.2.2

# Dev
No dev packages
```

**Comment by amiuhle** [comment]
**You should change your Redmine API Key!**

Sorry about that, I'll have to see if I can somehow omit it in bug reports created by Atom.
Thanks for reporting the issue, maybe I'll get something done over the holidays.
